name: shelf_exception_response
version: 0.1.0
description: Shelf middleware that provides the abillity to simply throw an HttpException that gets converted to an appropriate response code and a formatted response body dependent on clients accept header.
homepage: https://github.com/octobyte/shelf_exception_response
author: Thomas Profelt <tom@octobyte.at>

dependencies:
  shelf: any

dev_dependencies:
  unittest: any

environment:
  sdk: ">=1.3.0"